name: Database Migration

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
      - '.github/workflows/database.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
      - '.github/workflows/database.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy migrations'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  validate-migrations:
    name: Validate Migrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase start

      - name: Run migration validation script
        run: ./scripts/validate-migrations.sh

      - name: Stop Supabase
        run: supabase stop

  deploy-dev:
    name: Deploy to Development
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: ubuntu-latest
    needs: [validate-migrations]
    environment: development
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy migrations
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Generate and commit types
        run: |
          supabase gen types typescript > src/types/supabase.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/types/supabase.ts; then
            echo "Types updated after migration deployment"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add src/types/supabase.ts
            git commit -m "chore: update Supabase types after migration deployment [skip ci]"
            git push
          fi

  deploy-prod:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
    runs-on: ubuntu-latest
    needs: [validate-migrations]
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy migrations
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Generate types
        run: supabase gen types typescript > src/types/supabase.ts