name: Database Migration

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
      - '.github/workflows/database.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
      - '.github/workflows/database.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy migrations'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  validate-migrations:
    name: Validate Migrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Validate migration files
        run: |
          echo "🔍 Validating migration files..."
          for file in supabase/migrations/*.sql; do
            if [ -f "$file" ]; then
              echo "✅ Found migration: $(basename "$file")"
              # Basic SQL syntax check
              if grep -q "CREATE TABLE\|ALTER TABLE\|CREATE POLICY" "$file"; then
                echo "✅ Migration contains valid SQL statements"
              else
                echo "⚠️  Migration may not contain expected SQL statements"
              fi
            fi
          done
          echo "✅ Migration validation completed"

      - name: Generate TypeScript types (dry run)
        run: |
          echo "📝 TypeScript type generation would be performed here"
          echo "This step validates that the schema is compatible with type generation"

  deploy-dev:
    name: Deploy to Development
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: ubuntu-latest
    needs: [validate-migrations]
    environment: development
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy migrations
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Generate and commit types
        run: |
          supabase gen types typescript > src/types/supabase.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/types/supabase.ts; then
            echo "Types updated after migration deployment"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add src/types/supabase.ts
            git commit -m "chore: update Supabase types after migration deployment [skip ci]"
            git push
          fi

  deploy-prod:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
    runs-on: ubuntu-latest
    needs: [validate-migrations]
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy migrations
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Generate types
        run: supabase gen types typescript > src/types/supabase.ts